# Generated by Django 5.2.5 on 2025-09-25 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('aceptado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manuscrito',
                'verbose_name_plural': 'Manuscritos',
            },
        ),
        migrations.CreateModel(
            name='ArchivoManuscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='manuscritos/')),
                ('manuscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='manuscritos.manuscrito')),
            ],
            options={
                'verbose_name': 'Archivo de Manuscrito',
                'verbose_name_plural': 'Archivos de Manuscritos',
            },
        ),
    ]
